// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package provider

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type TeamCreateInput struct {
	// Period after which closed and completed issues are automatically archived, in months. 0 means disabled.
	AutoArchivePeriod float64 `json:"autoArchivePeriod"`
	// Period after which issues are automatically closed, in months.
	AutoClosePeriod float64 `json:"autoClosePeriod"`
	// The canceled workflow state which auto closed issues will be set to.
	AutoCloseStateId string `json:"autoCloseStateId"`
	// The color of the team.
	Color string `json:"color"`
	// The cooldown time after each cycle in weeks.
	CycleCooldownTime int `json:"cycleCooldownTime"`
	// The duration of each cycle in weeks.
	CycleDuration int `json:"cycleDuration"`
	// Auto assign completed issues to current active cycle setting.
	CycleIssueAutoAssignCompleted bool `json:"cycleIssueAutoAssignCompleted"`
	// Auto assign started issues to current active cycle setting.
	CycleIssueAutoAssignStarted bool `json:"cycleIssueAutoAssignStarted"`
	// Only allow issues issues with cycles in Active Issues.
	CycleLockToActive bool `json:"cycleLockToActive"`
	// The day of the week that a new cycle starts.
	CycleStartDay float64 `json:"cycleStartDay"`
	// Whether the team uses cycles.
	CyclesEnabled bool `json:"cyclesEnabled"`
	// What to use as an default estimate for unestimated issues.
	DefaultIssueEstimate float64 `json:"defaultIssueEstimate"`
	// The identifier of the default template for members of this team.
	DefaultTemplateForMembersId string `json:"defaultTemplateForMembersId"`
	// The identifier of the default template for non-members of this team.
	DefaultTemplateForNonMembersId string `json:"defaultTemplateForNonMembersId"`
	// The description of the team.
	Description string `json:"description"`
	// Whether to group recent issue history entries.
	GroupIssueHistory bool `json:"groupIssueHistory"`
	// The icon of the team.
	Icon string `json:"icon"`
	// The identifier. If none is provided, the backend will generate one.
	Id string `json:"id"`
	// Whether to allow zeros in issues estimates.
	IssueEstimationAllowZero bool `json:"issueEstimationAllowZero"`
	// Whether to add additional points to the estimate scale.
	IssueEstimationExtended bool `json:"issueEstimationExtended"`
	// The issue estimation type to use.
	IssueEstimationType string `json:"issueEstimationType"`
	// Whether issues without priority should be sorted first.
	IssueOrderingNoPriorityFirst bool `json:"issueOrderingNoPriorityFirst"`
	// The key of the team. If not given, the key will be generated based on the name of the team.
	Key string `json:"key"`
	// The workflow state into which issues are moved when they are marked as a duplicate of another issue.
	MarkedAsDuplicateWorkflowStateId string `json:"markedAsDuplicateWorkflowStateId"`
	// The name of the team.
	Name string `json:"name"`
	// The organization associated with the team.
	OrganizationId string `json:"organizationId"`
	// Internal. Whether the team is private or not.
	Private bool `json:"private"`
	// The timezone of the team.
	Timezone string `json:"timezone"`
	// Whether triage mode is enabled for the team.
	TriageEnabled bool `json:"triageEnabled"`
	// How many upcoming cycles to create.
	UpcomingCycleCount float64 `json:"upcomingCycleCount"`
}

// GetAutoArchivePeriod returns TeamCreateInput.AutoArchivePeriod, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetAutoArchivePeriod() float64 { return v.AutoArchivePeriod }

// GetAutoClosePeriod returns TeamCreateInput.AutoClosePeriod, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetAutoClosePeriod() float64 { return v.AutoClosePeriod }

// GetAutoCloseStateId returns TeamCreateInput.AutoCloseStateId, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetAutoCloseStateId() string { return v.AutoCloseStateId }

// GetColor returns TeamCreateInput.Color, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetColor() string { return v.Color }

// GetCycleCooldownTime returns TeamCreateInput.CycleCooldownTime, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleCooldownTime() int { return v.CycleCooldownTime }

// GetCycleDuration returns TeamCreateInput.CycleDuration, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleDuration() int { return v.CycleDuration }

// GetCycleIssueAutoAssignCompleted returns TeamCreateInput.CycleIssueAutoAssignCompleted, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleIssueAutoAssignCompleted() bool {
	return v.CycleIssueAutoAssignCompleted
}

// GetCycleIssueAutoAssignStarted returns TeamCreateInput.CycleIssueAutoAssignStarted, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleIssueAutoAssignStarted() bool { return v.CycleIssueAutoAssignStarted }

// GetCycleLockToActive returns TeamCreateInput.CycleLockToActive, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleLockToActive() bool { return v.CycleLockToActive }

// GetCycleStartDay returns TeamCreateInput.CycleStartDay, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCycleStartDay() float64 { return v.CycleStartDay }

// GetCyclesEnabled returns TeamCreateInput.CyclesEnabled, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetCyclesEnabled() bool { return v.CyclesEnabled }

// GetDefaultIssueEstimate returns TeamCreateInput.DefaultIssueEstimate, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetDefaultIssueEstimate() float64 { return v.DefaultIssueEstimate }

// GetDefaultTemplateForMembersId returns TeamCreateInput.DefaultTemplateForMembersId, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetDefaultTemplateForMembersId() string {
	return v.DefaultTemplateForMembersId
}

// GetDefaultTemplateForNonMembersId returns TeamCreateInput.DefaultTemplateForNonMembersId, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetDefaultTemplateForNonMembersId() string {
	return v.DefaultTemplateForNonMembersId
}

// GetDescription returns TeamCreateInput.Description, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetDescription() string { return v.Description }

// GetGroupIssueHistory returns TeamCreateInput.GroupIssueHistory, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetGroupIssueHistory() bool { return v.GroupIssueHistory }

// GetIcon returns TeamCreateInput.Icon, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetIcon() string { return v.Icon }

// GetId returns TeamCreateInput.Id, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetId() string { return v.Id }

// GetIssueEstimationAllowZero returns TeamCreateInput.IssueEstimationAllowZero, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetIssueEstimationAllowZero() bool { return v.IssueEstimationAllowZero }

// GetIssueEstimationExtended returns TeamCreateInput.IssueEstimationExtended, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetIssueEstimationExtended() bool { return v.IssueEstimationExtended }

// GetIssueEstimationType returns TeamCreateInput.IssueEstimationType, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetIssueEstimationType() string { return v.IssueEstimationType }

// GetIssueOrderingNoPriorityFirst returns TeamCreateInput.IssueOrderingNoPriorityFirst, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetIssueOrderingNoPriorityFirst() bool {
	return v.IssueOrderingNoPriorityFirst
}

// GetKey returns TeamCreateInput.Key, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetKey() string { return v.Key }

// GetMarkedAsDuplicateWorkflowStateId returns TeamCreateInput.MarkedAsDuplicateWorkflowStateId, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetMarkedAsDuplicateWorkflowStateId() string {
	return v.MarkedAsDuplicateWorkflowStateId
}

// GetName returns TeamCreateInput.Name, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetName() string { return v.Name }

// GetOrganizationId returns TeamCreateInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetOrganizationId() string { return v.OrganizationId }

// GetPrivate returns TeamCreateInput.Private, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetPrivate() bool { return v.Private }

// GetTimezone returns TeamCreateInput.Timezone, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetTimezone() string { return v.Timezone }

// GetTriageEnabled returns TeamCreateInput.TriageEnabled, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetTriageEnabled() bool { return v.TriageEnabled }

// GetUpcomingCycleCount returns TeamCreateInput.UpcomingCycleCount, and is useful for accessing the field via an interface.
func (v *TeamCreateInput) GetUpcomingCycleCount() float64 { return v.UpcomingCycleCount }

// __createTeamInput is used internally by genqlient
type __createTeamInput struct {
	Input TeamCreateInput `json:"input"`
}

// GetInput returns __createTeamInput.Input, and is useful for accessing the field via an interface.
func (v *__createTeamInput) GetInput() TeamCreateInput { return v.Input }

// __deleteTeamInput is used internally by genqlient
type __deleteTeamInput struct {
	Key string `json:"key"`
}

// GetKey returns __deleteTeamInput.Key, and is useful for accessing the field via an interface.
func (v *__deleteTeamInput) GetKey() string { return v.Key }

// __getTeamInput is used internally by genqlient
type __getTeamInput struct {
	Key string `json:"key"`
}

// GetKey returns __getTeamInput.Key, and is useful for accessing the field via an interface.
func (v *__getTeamInput) GetKey() string { return v.Key }

// createTeamResponse is returned by createTeam on success.
type createTeamResponse struct {
	// Creates a new team. The user who creates the team will automatically be added as a member to the newly created team.
	TeamCreate createTeamTeamCreateTeamPayload `json:"teamCreate"`
}

// GetTeamCreate returns createTeamResponse.TeamCreate, and is useful for accessing the field via an interface.
func (v *createTeamResponse) GetTeamCreate() createTeamTeamCreateTeamPayload { return v.TeamCreate }

// createTeamTeamCreateTeamPayload includes the requested fields of the GraphQL type TeamPayload.
type createTeamTeamCreateTeamPayload struct {
	// The team that was created or updated.
	Team createTeamTeamCreateTeamPayloadTeam `json:"team"`
}

// GetTeam returns createTeamTeamCreateTeamPayload.Team, and is useful for accessing the field via an interface.
func (v *createTeamTeamCreateTeamPayload) GetTeam() createTeamTeamCreateTeamPayloadTeam {
	return v.Team
}

// createTeamTeamCreateTeamPayloadTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// An organizational unit that contains issues.
type createTeamTeamCreateTeamPayloadTeam struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The team's name.
	Name string `json:"name"`
	// The team's unique key. The key is used in URLs.
	Key string `json:"key"`
	// The team's description.
	Description string `json:"description"`
	// The icon of the team.
	Icon string `json:"icon"`
	// The team's color.
	Color string `json:"color"`
}

// GetId returns createTeamTeamCreateTeamPayloadTeam.Id, and is useful for accessing the field via an interface.
func (v *createTeamTeamCreateTeamPayloadTeam) GetId() string { return v.Id }

// GetName returns createTeamTeamCreateTeamPayloadTeam.Name, and is useful for accessing the field via an interface.
func (v *createTeamTeamCreateTeamPayloadTeam) GetName() string { return v.Name }

// GetKey returns createTeamTeamCreateTeamPayloadTeam.Key, and is useful for accessing the field via an interface.
func (v *createTeamTeamCreateTeamPayloadTeam) GetKey() string { return v.Key }

// GetDescription returns createTeamTeamCreateTeamPayloadTeam.Description, and is useful for accessing the field via an interface.
func (v *createTeamTeamCreateTeamPayloadTeam) GetDescription() string { return v.Description }

// GetIcon returns createTeamTeamCreateTeamPayloadTeam.Icon, and is useful for accessing the field via an interface.
func (v *createTeamTeamCreateTeamPayloadTeam) GetIcon() string { return v.Icon }

// GetColor returns createTeamTeamCreateTeamPayloadTeam.Color, and is useful for accessing the field via an interface.
func (v *createTeamTeamCreateTeamPayloadTeam) GetColor() string { return v.Color }

// deleteTeamResponse is returned by deleteTeam on success.
type deleteTeamResponse struct {
	// Deletes a team.
	TeamDelete deleteTeamTeamDeleteArchivePayload `json:"teamDelete"`
}

// GetTeamDelete returns deleteTeamResponse.TeamDelete, and is useful for accessing the field via an interface.
func (v *deleteTeamResponse) GetTeamDelete() deleteTeamTeamDeleteArchivePayload { return v.TeamDelete }

// deleteTeamTeamDeleteArchivePayload includes the requested fields of the GraphQL type ArchivePayload.
type deleteTeamTeamDeleteArchivePayload struct {
	// Whether the operation was successful.
	Success bool `json:"success"`
}

// GetSuccess returns deleteTeamTeamDeleteArchivePayload.Success, and is useful for accessing the field via an interface.
func (v *deleteTeamTeamDeleteArchivePayload) GetSuccess() bool { return v.Success }

// getTeamResponse is returned by getTeam on success.
type getTeamResponse struct {
	// One specific team.
	Team getTeamTeam `json:"team"`
}

// GetTeam returns getTeamResponse.Team, and is useful for accessing the field via an interface.
func (v *getTeamResponse) GetTeam() getTeamTeam { return v.Team }

// getTeamTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// An organizational unit that contains issues.
type getTeamTeam struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The team's name.
	Name string `json:"name"`
	// The team's unique key. The key is used in URLs.
	Key string `json:"key"`
	// The team's description.
	Description string `json:"description"`
}

// GetId returns getTeamTeam.Id, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetId() string { return v.Id }

// GetName returns getTeamTeam.Name, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetName() string { return v.Name }

// GetKey returns getTeamTeam.Key, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetKey() string { return v.Key }

// GetDescription returns getTeamTeam.Description, and is useful for accessing the field via an interface.
func (v *getTeamTeam) GetDescription() string { return v.Description }

// getWorkspaceOrganization includes the requested fields of the GraphQL type Organization.
// The GraphQL type's documentation follows.
//
// An organization. Organizations are root-level objects that contain user accounts and teams.
type getWorkspaceOrganization struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The organization's unique URL key.
	UrlKey string `json:"urlKey"`
	// The organization's name.
	Name string `json:"name"`
}

// GetId returns getWorkspaceOrganization.Id, and is useful for accessing the field via an interface.
func (v *getWorkspaceOrganization) GetId() string { return v.Id }

// GetUrlKey returns getWorkspaceOrganization.UrlKey, and is useful for accessing the field via an interface.
func (v *getWorkspaceOrganization) GetUrlKey() string { return v.UrlKey }

// GetName returns getWorkspaceOrganization.Name, and is useful for accessing the field via an interface.
func (v *getWorkspaceOrganization) GetName() string { return v.Name }

// getWorkspaceResponse is returned by getWorkspace on success.
type getWorkspaceResponse struct {
	// The user's organization.
	Organization getWorkspaceOrganization `json:"organization"`
}

// GetOrganization returns getWorkspaceResponse.Organization, and is useful for accessing the field via an interface.
func (v *getWorkspaceResponse) GetOrganization() getWorkspaceOrganization { return v.Organization }

func createTeam(
	ctx context.Context,
	client graphql.Client,
	input TeamCreateInput,
) (*createTeamResponse, error) {
	req := &graphql.Request{
		OpName: "createTeam",
		Query: `
mutation createTeam ($input: TeamCreateInput!) {
	teamCreate(input: $input) {
		team {
			id
			name
			key
			description
			icon
			color
		}
	}
}
`,
		Variables: &__createTeamInput{
			Input: input,
		},
	}
	var err error

	var data createTeamResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func deleteTeam(
	ctx context.Context,
	client graphql.Client,
	key string,
) (*deleteTeamResponse, error) {
	req := &graphql.Request{
		OpName: "deleteTeam",
		Query: `
mutation deleteTeam ($key: String!) {
	teamDelete(id: $key) {
		success
	}
}
`,
		Variables: &__deleteTeamInput{
			Key: key,
		},
	}
	var err error

	var data deleteTeamResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func getTeam(
	ctx context.Context,
	client graphql.Client,
	key string,
) (*getTeamResponse, error) {
	req := &graphql.Request{
		OpName: "getTeam",
		Query: `
query getTeam ($key: String!) {
	team(id: $key) {
		id
		name
		key
		description
	}
}
`,
		Variables: &__getTeamInput{
			Key: key,
		},
	}
	var err error

	var data getTeamResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func getWorkspace(
	ctx context.Context,
	client graphql.Client,
) (*getWorkspaceResponse, error) {
	req := &graphql.Request{
		OpName: "getWorkspace",
		Query: `
query getWorkspace {
	organization {
		id
		urlKey
		name
	}
}
`,
	}
	var err error

	var data getWorkspaceResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
